// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp02jbEFKSLunszFFXS8vqkviK71ypTp8',
    appId: '1:65061542918:web:f0d55f197fbc1fc084f787',
    messagingSenderId: '65061542918',
    projectId: 'computology-9952d',
    authDomain: 'computology-9952d.firebaseapp.com',
    storageBucket: 'computology-9952d.firebasestorage.app',
    measurementId: 'G-5R3Q15F3KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrxOVVPbz-wBMu2B44Irs6T0eROD_wca8',
    appId: '1:65061542918:android:bf9ce8a69a1fc68784f787',
    messagingSenderId: '65061542918',
    projectId: 'computology-9952d',
    storageBucket: 'computology-9952d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQDjW8fXB9BB0EpPFlVc98GdWvx6WR-iY',
    appId: '1:65061542918:ios:b5c57e89e81351f684f787',
    messagingSenderId: '65061542918',
    projectId: 'computology-9952d',
    storageBucket: 'computology-9952d.firebasestorage.app',
    iosBundleId: 'com.example.computology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQDjW8fXB9BB0EpPFlVc98GdWvx6WR-iY',
    appId: '1:65061542918:ios:b5c57e89e81351f684f787',
    messagingSenderId: '65061542918',
    projectId: 'computology-9952d',
    storageBucket: 'computology-9952d.firebasestorage.app',
    iosBundleId: 'com.example.computology',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp02jbEFKSLunszFFXS8vqkviK71ypTp8',
    appId: '1:65061542918:web:050ddae78f9bd06784f787',
    messagingSenderId: '65061542918',
    projectId: 'computology-9952d',
    authDomain: 'computology-9952d.firebaseapp.com',
    storageBucket: 'computology-9952d.firebasestorage.app',
    measurementId: 'G-JMGB58DJB4',
  );
}
